Repository munich-quantum-toolkit/ddsim, pull requests merged in 2023-03, with the labels that each got.

#199 Add cpp-linter action
  .clang-tidy
  .github/workflows/cpp-linter.yml
  .gitignore
  apps/frqi.cpp
  apps/noise_aware.cpp
  apps/primebases.cpp
  apps/simple.cpp
  apps/vectors.cpp
  include/CircuitSimulator.hpp
  include/DeterministicNoiseSimulator.hpp
  include/GroverSimulator.hpp
  include/HybridSchrodingerFeynmanSimulator.hpp
  include/PathSimulator.hpp
  include/ShorFastSimulator.hpp
  include/ShorSimulator.hpp
  include/Simulator.hpp
  include/StochasticNoiseSimulator.hpp
  include/UnitarySimulator.hpp
  mqt/ddsim/bindings.cpp
  src/CircuitSimulator.cpp
  src/DeterministicNoiseSimulator.cpp
  src/GroverSimulator.cpp
  src/HybridSchrodingerFeynmanSimulator.cpp
  src/PathSimulator.cpp
  src/ShorFastSimulator.cpp
  src/ShorSimulator.cpp
  src/Simulator.cpp
  src/StochasticNoiseSimulator.cpp
  src/UnitarySimulator.cpp
  test/benchmark.cpp
  test/test_circuit_sim.cpp
  test/test_det_noise_sim.cpp
  test/test_fast_shor_sim.cpp
  test/test_grover_sim.cpp
  test/test_hybridsim.cpp
  test/test_path_sim.cpp
  test/test_shor_sim.cpp
  test/test_stoch_noise_sim.cpp
  test/test_unitary_sim.cpp
Labels: enhancement

#202 ✨ Expose tolerance and node counts to Python
  include/Simulator.hpp
  mqt/ddsim/bindings.cpp
  test/test_circuit_sim.cpp
Labels: enhancement

#203 ✨ Expose expectation value computation from DD Package to DDSIM
  include/CircuitSimulator.hpp
  mqt/ddsim/bindings.cpp
  src/CircuitSimulator.cpp
  test/python/simulator/test_standalone_simulator.py
  test/test_circuit_sim.cpp
Labels: enhancement

#206 🔧 Add release drafter workflow
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: continuous integration

#213 Added notebook of simulators to docs
  .pre-commit-config.yaml
  .readthedocs.yaml
  docs/source/Usage.ipynb
  docs/source/conf.py
  docs/source/index.rst
  pyproject.toml
Labels: documentation, enhancement

#217 Update clang-format version for pre-commit
  .github/workflows/cpp-linter.yml
  .pre-commit-config.yaml
Labels: enhancement, dependencies, continuous integration
